### ISSUE TITLE
No option 2

### ISSUE THREAD

**Issue by jeffhuys** [braver/PhpStorm-Solarized#4]
I've noticed that you talk about the manual installation option as if there's another option. I can't seem to find it, is manual installation the only way to install this?

**Comment by jaspernbrouwer** [comment]
### Option 2: Import settings

1. Clone (or download) this repository.
2. Go to `File | Import Settings` select the directory and click `Choose`.
3. Check `Color schemes` and press `Ok`.
4. Restart PhpStorm.
5. Go to `Preferences | Editor | Colors & Fonts` and select one of the new color themes.

**Comment by jeffhuys** [comment]
:+1:
